# Generated by Django 3.2.5 on 2021-08-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=45654, max_length=10, unique=True, verbose_name='Phone number'),
            preserve_default=False,
        ),
    ]
