# Generated by Django 3.2.5 on 2021-07-30 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210729_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_type',
        ),
        migrations.RemoveField(
            model_name='productimages',
            name='product',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='ColorVariant',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductImages',
        ),
        migrations.DeleteModel(
            name='QuantityVariant',
        ),
        migrations.DeleteModel(
            name='SizeVariant',
        ),
    ]
